[package]
name = "bitbit"
version = "0.1.2"
description = "Bit-at-a-time reader/writer types"
license = "MIT"
authors = ["Robert Norris <robn@robn.io>"]
repository  = "https://github.com/robn/bitbit-rs"
